config/routes.rb
Rails.application.routes.draw do
  resources :mazes, except: [:edit, :update]
  root to: 'mazes#index'
end

app/models/maze.rb
require 'depth_first'

class Maze < ActiveRecord::Base
  store_accessor :data, :start, :end, :width, :height, :grid
  validates_numericality_of :width, :height, less_than_or_equal_to: 30
  before_create :generate_grid

  def to_s
    @as_string ||= algorithm.to_s
  end

  private

  def generate_grid
    self.grid = algorithm.grid
    self.start = algorithm.start
    self.end = algorithm.end
  end

  def algorithm
    @algorithm ||= DepthFirst.new(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mazes_controller.rb
class MazesController < ApplicationController
  before_action :set_maze, only: [:show, :edit, :update, :destroy]

  # GET /mazes
  # GET /mazes.json
  def index
    @mazes = Maze.all
  end

  # GET /mazes/1
  # GET /mazes/1.json
  def show
  end

  # GET /mazes/new
  def new
    @maze = Maze.new
  end

  # POST /mazes
  # POST /mazes.json
  def create
    @maze = Maze.new(maze_params)

    respond_to do |format|
      if @maze.save
        format.html { redirect_to @maze, notice: 'Maze was successfully created.' }
        format.json { render :show, status: :created, location: @maze }
      else
        format.html { render :new }
        format.json { render json: @maze.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mazes/1
  # DELETE /mazes/1.json
  def destroy
    @maze.destroy
    respond_to do |format|
      format.html { redirect_to mazes_url, notice: 'Maze was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maze
      @maze = Maze.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maze_params
      params.require(:maze).permit(:width, :height)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MazeExercise</title>
  <link href="http://d2v52k3cl9vedd.cloudfront.net/basscss/7.0.4/basscss.min.css" rel="stylesheet">  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container p2">
<%= yield %>
</div>
</body>
</html>

app/views/mazes/_form.html.erb
<%= form_for(@maze) do |f| %>
  <% if @maze.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maze.errors.count, "error") %> prohibited this maze from being saved:</h2>

      <ul>
      <% @maze.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb2">
    <%= f.label :width %><br>
    <%= f.text_field :width, class: 'field' %>
  </div>
  <div class="mb2">
    <%= f.label :height %><br>
    <%= f.text_field :height, class: 'field' %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/mazes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mazes</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Width</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mazes.each do |maze| %>
      <tr>
        <td><%= maze.id %></td>
        <td><%= maze.width %></td>
        <td><%= maze.height %></td>
        <td><%= link_to 'Show', maze %></td>
        <td><%= link_to 'Destroy', maze, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maze', new_maze_path %>

app/views/mazes/new.html.erb
<h1>New Maze</h1>

<%= render 'form' %>

<%= link_to 'Back', mazes_path %>

app/views/mazes/show.html.erb
<p id="notice"><%= notice %></p>


<pre class="bg-blue white inline-block p2"><%== @maze %></pre>

<p>
  <strong>Width:</strong>
  <%= @maze.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @maze.height %>
</p>

<%= link_to 'Solve', '#', id: 'solve', data: {maze: @maze.to_json} %>
<%= link_to 'Back', mazes_path %>
<%= link_to 'Destroy', @maze, method: :delete, data: { confirm: 'Are you sure?' } %>